api:
  dashboard: true
  insecure: true
entryPoints:
  http:
    address: ':80'
    forwardedHeaders:
      trustedIPs:
        - 127.0.0.1/32
        - 192.168.8.0/24
  https:
    address: ':443'
    http:
      tls: {}
    forwardedHeaders:
      trustedIPs:
        - 127.0.0.1/32
        - 192.168.8.0/24
  traefik:
    address: 127.0.0.1:8080
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    defaultRule: Host(`{{ index .Labels "com.docker.compose.service"}}.mydomain.net`)
    network: proxy
  file:
    directory: /etc/traefik/dynamic
    watch: true
certificatesResolvers:
  cloudflare:
    acme:
      email: cloudflare@mydomain.net
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        disablePropagationCheck: true
        delayBeforeCheck: 20s
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53
serversTransport:
  insecureSkipVerify: false
accessLog:
  filePath: /var/log/traefik/access.log
  fields:
    headers:
      names:
        User-Agent: keep
log:
  filePath: /var/log/traefik/traefik.log
  level: DEBUG
